import * as vscode from "vscode";

/**
 * Inlay hints provider for FANUC TP programs.
 * Provides contextual hints for auto-updated fields and stripped line numbers.
 */
export class FanucTpInlayHintsProvider implements vscode.InlayHintsProvider {
  /**
   * Provide inlay hints for a document.
   */
  provideInlayHints(
    document: vscode.TextDocument,
    _range: vscode.Range,
    _token: vscode.CancellationToken
  ): vscode.InlayHint[] {
    const hints: vscode.InlayHint[] = [];
    const text = document.getText();
    const lines = text.split("\n");

    // Track if we're in the /ATTR section
    let inAttrSection = false;
    let mnLineIndex = -1;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];

      // Detect /ATTR section start
      if (/^\/ATTR\s*$/.test(line)) {
        inAttrSection = true;
        continue;
      }

      // Detect /ATTR section end
      if (inAttrSection && /^\/[A-Z]+/.test(line) && !/^\/ATTR/.test(line)) {
        inAttrSection = false;
      }

      // Process auto-updated fields in /ATTR section
      if (inAttrSection) {
        this.processAutoUpdatedField(document, line, i, hints);
      }

      // Track /MN line for line number check
      if (/^\/MN\s*$/.test(line)) {
        mnLineIndex = i;
      }
    }

    // Check for stripped line numbers after /MN
    if (mnLineIndex >= 0 && mnLineIndex + 1 < lines.length) {
      this.processStrippedLineNumbers(document, lines, mnLineIndex, hints);
    }

    return hints;
  }

  /**
   * Process auto-updated fields and add hints for zeroed values.
   */
  private processAutoUpdatedField(
    document: vscode.TextDocument,
    line: string,
    lineIndex: number,
    hints: vscode.InlayHint[]
  ): void {
    // Check for PROG_SIZE = 0;
    const progSizeMatch = /^(PROG_SIZE\s*=\s*0)\s*;/.exec(line);
    if (progSizeMatch) {
      this.addAutoUpdatedHint(document, lineIndex, progSizeMatch[1], hints);
      return;
    }

    // Check for MODIFIED = DATE 24-01-01  TIME 00:00:00;
    const modifiedMatch = /^(MODIFIED\s*=\s*DATE\s+24-01-01\s+TIME\s+00:00:00)\s*;/.exec(line);
    if (modifiedMatch) {
      this.addAutoUpdatedHint(document, lineIndex, modifiedMatch[1], hints);
      return;
    }

    // Check for LINE_COUNT = 0;
    const lineCountMatch = /^(LINE_COUNT\s*=\s*0)\s*;/.exec(line);
    if (lineCountMatch) {
      this.addAutoUpdatedHint(document, lineIndex, lineCountMatch[1], hints);
      return;
    }

    // Check for MEMORY_SIZE = 0;
    const memorySizeMatch = /^(MEMORY_SIZE\s*=\s*0)\s*;/.exec(line);
    if (memorySizeMatch) {
      this.addAutoUpdatedHint(document, lineIndex, memorySizeMatch[1], hints);
      return;
    }
  }

  /**
   * Add an auto-updated field hint.
   */
  private addAutoUpdatedHint(
    document: vscode.TextDocument,
    lineIndex: number,
    matchedText: string,
    hints: vscode.InlayHint[]
  ): void {
    const line = document.lineAt(lineIndex);
    const endPos = new vscode.Position(lineIndex, line.text.indexOf(matchedText) + matchedText.length);

    const hint = new vscode.InlayHint(
      endPos,
      " ← Values auto-generated by controller on upload",
      vscode.InlayHintKind.Parameter
    );
    hint.paddingLeft = true;
    hints.push(hint);
  }

  /**
   * Process stripped line numbers after /MN.
   */
  private processStrippedLineNumbers(
    document: vscode.TextDocument,
    lines: string[],
    mnLineIndex: number,
    hints: vscode.InlayHint[]
  ): void {
    // Check the first line after /MN
    const firstLineAfterMn = lines[mnLineIndex + 1];

    // Check if line numbers are stripped (line starts with ':' after whitespace)
    // Pattern: optional whitespace, then ':', indicating no line number
    const strippedMatch = /^\s+:/.exec(firstLineAfterMn);

    if (strippedMatch) {
      // Line numbers are stripped, add hint to /MN line
      const mnLine = document.lineAt(mnLineIndex);
      const endPos = new vscode.Position(mnLineIndex, mnLine.text.length);

      const hint = new vscode.InlayHint(
        endPos,
        " ← Line numbers auto-generated on upload",
        vscode.InlayHintKind.Parameter
      );
      hint.paddingLeft = true;
      hints.push(hint);
    }
  }
}
